### PR TITLE
Adding relative path for filename

### PR DESCRIPTION
**Pull request by tebriel**
The standard formatters for rubocop use the relative_path utility, for example on the json formatter:
https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/formatter/json_formatter.rb#L49

This is super helpful in Jenkins.

### CODE REVIEW

**Comment by eitoball** [comment]
@tebriel Thank you for PR. Since, Since Travis CI was red, so I just borrowed your idea and created 89f6c5f0ac8b032ecdd7027b8f16e5dee3aa77dd.

**Comment by tebriel** [comment]
@eitoball Thanks for the merge! I spent a bit trying to fix travis, but the answer wasn't immediately visible to me. Thanks for fixing that too!

**Comment by jh125486** [comment]
I know the `relative_path` is the preferred way for rubocop, but my install of Jenkins violations plugin (v0.7.11) does not like the relative path of violating files and does not put the `<error line=xx/>`  elements into the `violations/file/violating_file.xml`.  
This makes the per file violations page blank for each file.

Should I need to set the `Faux Project Path` in the violations plugin or am I missing something else?

**Comment by tebriel** [comment]
I could never get the Violations plugin to work, I'm now using the CheckStyle plugin and it works solidly without issue.

https://wiki.jenkins-ci.org/display/JENKINS/Checkstyle+Plugin




On May 6, 2015 at 4:07:16 PM, Jacob Hochstetler (notifications@github.com<mailto:notifications@github.com>) wrote:

I know the relative_path is the preferred way for rubocop, but my install of Jenkins violations plugin (v0.7.11) does not like the relative path of violating files and does not put the <error line=xx/> elements into the violations/file/violating_file.xml.

This makes the per file violations page blank for each file.

Should I need to set the Faux Project Path in the violations plugin or am I missing something else?

**Comment by eitoball** [comment]
@jh125486 Sorry for your trouble. I am using checkstyle plugin, so I didn't notice that changing to relative path causes such issue. Please use version 0.1.1 if possible. I created #9, and try to fix in next release. Thank you.

**Pull request closed without merging**
